### ISSUE TITLE
Tokenizer bug?

### ISSUE THREAD

**Issue by stanleyjs** [molML/s4-for-de-novo-drug-design#8]
Hello,

I am attempting to follow your pipeline for generating molecules. I noticed that if I train with the ChemBL mini dataset, I get 36 tokens, although the model's default vocabulary size is 37. When I attempt to generate using temperatures larger than 1, I end up with out-of-vocabulary tokens. 

Is this a bug or am I missing something? I noticed that there is no place to control the vocabulary size in the smiles tokenizer.

Thanks

**Comment by rizaozcelik** [comment]
Hello Jay,

You can provide a `vocab_size` while creating a `S4forDenovoDesign` instance to train with custom vocabularies.

If you run the pipeline with the mini dataset and default configurations, you might end up with models that design "weird" molecules due to under-training or bad model initialization. Such risks should be negligible for models trained long enough on larger datasets, though.

If you bump into any error while running the code, please share it here so I can help with more precision 🙂
